### ISSUE TITLE
PRESETS

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#13]
there were no presets in challenger and it was a huge pain so ye

**Comment by Ovikx** [comment]
What are presets tho

**Comment by nut4050** [comment]
like save slots where you can store setups of your armor and moves abnd mods n shi8t
it was more pertinent in challenger than in this since youre just switching out your weapons and armor tho so you can probably disregard this

**Comment by Ovikx** [comment]
Closing this bc the favorite gear command I have planned will bring this idea full circle

**Comment by nut4050** [comment]
HAWT
