### ISSUE TITLE
turn 1 retreat

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#19]
make it so if you retreat the turn a battle starts you don't lose elo bc otherwise ending an endless match is literally impossible

**Comment by Ovikx** [comment]
Then people would retreat whenever they feel they are about to lose, essentially cheesing the elo system

**Comment by Ovikx** [comment]
I think a good remedy is to make it sort of like pokemon where it has an n% chance of working with no elo loss

**Comment by nut4050** [comment]
that's why i suggested specifically turn 1

**Comment by nut4050** [comment]
bc turn 1 nothing has happened yet so there's nothing gained from retreating immediately

**Comment by nut4050** [comment]
if you don't make a way to leave an endless match without losing elo then endless becomes basically pointless because it's a guaranteed elo loss at the end

**Comment by Ovikx** [comment]
People can cheese the elo system by just retreating on higher-rated enemies
Consider the n% chance idea

**Comment by nut4050** [comment]
you could make it so the elo loss only works on non boss enemies and only if you're a certain amount stronger than the enemy
idk i'm just saying bc it's not really that rewarding to kill 35 enemies in endless mode just to lose 35 elo from being done playing for the time being

**Comment by Ovikx** [comment]
I think n% chance with no elo loss addresses this

**Comment by Ovikx** [comment]
(and it makes retreating cooler)

**Comment by nut4050** [comment]
the random chance is decent i guess but randomness isn't exactly fun when it can negatively impact you so people will just start letting the game time out which is super inconvenient

**Comment by Ovikx** [comment]
mmm muy interesante amigo
thought about it and i realized that retreating to avoid losing won't matter a lot because eventually even the weakest enemies will be able to beat you
gonna try to implement your original suggestion

**Comment by Ovikx** [comment]
Done
