### ISSUE TITLE
add rebirths

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#2]
- add rebirths fr sheesh### ### **_**_**_**_****_**
![D6CCFBB1-CE7E-46F9-A48E-A2D1D83DCD2E](https://user-images.githubusercontent.com/109875839/180621447-1c7bca8a-7f4d-4669-9f47-81630d2d085a.jpeg)
_**_**_**

**Comment by Ovikx** [comment]
what would be the point of rebirthing tho

**Comment by nut4050** [comment]
it’s awesome also

**Comment by nut4050** [comment]
it’s cool

**Comment by Ovikx** [comment]
yeah but i don't see a place for it
rebirthing (which i assume entails resetting your inventory and stats) would kill the point of collecting weapons and stuff
