### ISSUE TITLE
armor stats :(

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#21]
can you make the extent of the rng values for armor less wild bc the level of variation makes most armors completely unusable

**Comment by nut4050** [comment]
1900 damage frmo a bioome 2 enemy shouldnt bne a thing that can happen

**Comment by Ovikx** [comment]
skill issue

**Comment by Ovikx** [comment]
but i do like this idea

**Comment by Ovikx** [comment]
Added to todo

**Comment by Ovikx** [comment]
Done
