### ISSUE TITLE
weapon type specific moves

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#24]
going off the parry move for shield suggestion there should be more weapon-type-specific moves so that each weapon type is more unique bc rn the only differences (that i know of) are purely aesthetic

**Comment by nut4050** [comment]
if the moves are already like this then i'm dumb but add more

**Comment by Ovikx** [comment]
They have their own sets of moves already

Each weapon's move set has some moves that have no substitutes in other move sets

**Comment by nut4050** [comment]
hot

**Comment by nut4050** [comment]
you should add more tho

**Comment by Ovikx** [comment]
Already on todo
