### ISSUE TITLE
equipping more than one thing at a time

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#25]
could you make it so the equip command can take multiple inputs at once
eg. /equip 'abcd efgh'
this is kinda a first world issue so feel free to ignore

**Comment by Ovikx** [comment]
Important first world issue, though
Will add to todo once I figure out if it's feasible or not, but for now it's going in the Maybe category

**Comment by Ovikx** [comment]
Actually nvm it's going in todo bc it's a pretty important QOL change

**Comment by Ovikx** [comment]
done, will be pushed to stable version by november 1
