### ISSUE TITLE
additive referrals

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#31]
idk how thr referrals work yet bc no ones done any but could they work like where each referral gives u one more of each crate than the last so theres more benefit

already know this is gonnna get struck down

**Comment by Ovikx** [comment]
good thought, but i think it would be overpowered
right now, i think that flat rewards are the fairest, but there could be better solutions

**Comment by nut4050** [comment]
you should do (ln(x))^2

**Comment by Ovikx** [comment]
something of that sort; added to todo

**Comment by Ovikx** [comment]
done
