### ISSUE TITLE
add tiered crates

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#5]
only getting c class stuff the whole game sucks

idk this might already be in the plans but i still wanna complain about it

**Comment by Ovikx** [comment]
there's no point in adding them unless the probability of getting an *x*-class per coin spent changes across crate tiers.
having a few higher-tiered crates would have no statistical advantage over having lots of lower-tiered crates

**Comment by nut4050** [comment]
yeah but opening a thousand low tier crates for one s tier item is a massive pain
also giving new players access to the same equipment as experienced players is just wrong
like i shouldnt (with my 200 elo) be able to get the same items from the same crates as someone with say 1100 elo it just doesn’t make sense

**Comment by Ovikx** [comment]
1. opening multiple crates at once will address that
2. more experienced players will be able to purchase more crates (higher coin income), so they have a larger chance of getting good stuff. even if a noob gets an S class weapon, they won't be able to progress far without good mods/armor.

**Comment by nut4050** [comment]
i suppose that’s somewhat fair enough for now
