### ISSUE TITLE
revamp the biome progression system

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#59]
i feel like it's too easy to get all the way to the highest biome for free after like 3 minutes of gameplay so could u add like bosses or a required number of defeated enemies to progress through biomes
and then to prevent people from getting like 200 elo above their biome just bc that's how the elo system works you could just disable players from gaining elo above the max for their biome
but like as it stands the biome prog system is kinda cringe

**Comment by Ovikx** [comment]
I'd rather buff the 500+ elo enemies than kill the fluidity of progression; latter suggestion is good
