### ISSUE TITLE
lower damage randomness

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#61]

**Comment by Ovikx** [comment]
why

**Comment by nut4050** [comment]
too much rng 🧙🏿

**Comment by Ovikx** [comment]
that implies everything would have to get nerfed

**Comment by nut4050** [comment]
hm

**Comment by Ovikx** [comment]
how about reducing overlap between classes on the lower bound

**Comment by Unlamped** [comment]
would that make c tier worse, noooooo

**Comment by nut4050** [comment]
i don't think i explained this well but i meant in fights

like when you're in a fight the amount of damage your move can do on an enemy has a ton of range to it like you could do 41 or you could do 61 so just like make that range smaller

**Comment by Ovikx** [comment]
done

**Comment by Ovikx** [comment]
random damage multiplier range was reduced from [0.85, 1.15] to [0.90, 1.10]
