### ISSUE TITLE
inventory sort

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#7]
make it possible to more precisely sort inventory by like tier or something idk 
my inv always times out before i can even get to all of my high tier stuff bc its all so spread out so being able to flush all the good stuff to the front would save such an ungodly amount of time

**Comment by nut4050** [comment]
also could you separate the mod sort into armor mods, weapon mods, and generic mods
thx bb <3

**Comment by Ovikx** [comment]
Already on todo
