### ISSUE TITLE
Squad Coin give more

### ISSUE THREAD

**Issue by Unlamped** [Ovikx/exalt-public#70]
Participation: Squad coin should have participation amoutn, mabye like 10% of total for no participation, 20 for 1, 40% for 2, 60% for 3 80% for 4 and 100% for 5

Wins: The more you win the more squad coins you get and this would help more experienced/late game players get more squad coins while keeping it balanced for newer players, this could be like 50% more for all 5 wins and like a 10% reduction for 0 wins.

Research: I have an idea for another research branch, one that makes squad war give more squad coins.

**Comment by Ovikx** [comment]
i'm putting a hard maybe on individual-based squad war bonuses, but i like the research branch idea

**Comment by nut4050** [comment]
https://discord.com/channels/992574903482056815/992574903482056818/1084287638808313976
