### ISSUE TITLE
/sell-all except S and X

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#71]
where you can like configure the settings of like what tiers to sell of each item type that way you don’t need 9 commands to sell all your gear you don’t need

**Comment by Ovikx** [comment]
selling is already a computationally expensive task (each mod has to be unequipped from every weapon/armor that has it equipped), so i'm not the biggest proponent of this idea. i'd rather just add an option to the sell-all command that lets you sell everything except S and X

**Comment by nut4050** [comment]
that's chill 👌

**Comment by Ovikx** [comment]
done
