### ISSUE TITLE
skill for supercharged attacks

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#72]
idk how it would work but i want it

**Comment by Ovikx** [comment]
max energy hello?

**Comment by nut4050** [comment]
but then i have to actually get the more the energy in fight hghrbtbtsuab blooopoo

**Comment by Ovikx** [comment]
that's the point of supercharged attacks. there's also the pass energy skill which helps a ton.
plus, supercharged is already pretty good, so I don't see the point of adding another skill for it

**Comment by Ovikx** [comment]
closing this bc I really don't think this is a good idea
