### ISSUE TITLE
Uncapped vote rewards

### ISSUE THREAD

**Issue by Unlamped** [Ovikx/exalt-public#74]
Vote rewards are capped at 4 week
While daily is get progressively better and better as time goes.
Vote rewards just get worse as you play the game more as it becomes less relavant as you get more money overall.
I feel that vote rewards should also be buffed, mabye 1.5x per week is too much, mabye at the 4th week the rewards don't increase as fast, like mabye 1.25x per week, while also getting a large boost for every 50 votes just like daily, or like 80 or something since there are 2 votes per day.

**Comment by Ovikx** [comment]
added to todo; 50 coins will be added each week after 4th week

**Comment by Unlamped** [comment]
what does each week represent, 14 votes?

**Comment by Ovikx** [comment]
7

**Comment by Unlamped** [comment]
ok

**Comment by Ovikx** [comment]
done
