### ISSUE TITLE
[SUGGESTION] <Late Game>

### ISSUE THREAD

**Issue by Unlamped** [Ovikx/exalt-public#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Late Game in Exalt bot is not very fun, as it is just clicking the same button over and over again for a very minimal amount of coins for a miniscule chance at an x tiered item. There doesn't seem to be much to do now.

### Describe the solution you'd like

More ways of making money, that scale into late game.

### Describe the alternatives you've considered

Making more uses for money besides crates (merchant and squads don't use many coins lategame)

New ways to improve weapons and armour.

Allow higher elos to buy better items in the merchant (mabye at 10k elo you could by x tier items so it is something to work to, or at 2-3k elo to buy exalted mods from merchant)

**Comment by Ovikx** [comment]
A few questions:
1. "More ways of making money" doesn't articulate an actual solution. What would this look like in-game? 
2. "Making more uses for money besides crates" is also very vague. Again, what would this look like in-game?
3. What would the "new ways to improve weapons and armor" do that's different from `/upgrade-gear`?

We've already established that X-tier items will never be obtainable anywhere other than `/fight`.

Keep in mind that story/bosses are already in development. They will extend the depth of endgame by a lot.

**Comment by Unlamped** [comment]
Money idea: every once in a while above 500 elo, when doing fight commands a challenger will approach you who is like maybe 2x or 1.5x the current biome's enemies depending on your elo. It would be a very hard fight, but you will get x10 coins or something from this fight, and it may occur roughly every 100-1000 fights.

Money idea 2: Mercenary quests to go back to a specific biome and fight something there for money and/or crates. (or to fight a boss)

Money idea 3: beat up the merchant

**Comment by Ovikx** [comment]
What about the other two questions?

**Comment by Ovikx** [comment]
closing because stale; still note that bosses will give plenty of rewards
