### ISSUE TITLE
[SUGGESTION] View currently equipped items

### ISSUE THREAD

**Issue by FortiethAtom4** [Ovikx/exalt-public#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

As gameplay progresses and the player's inventory grows, it becomes increasingly difficult to manage your items. In particular, there is no concrete way of telling what items the player currently has equipped, making managing e.g. weapon and armor mods tedious and trial-and-error, or just a lot of /unequip-all which seems unnecessary.

After some experimenting, it seems a failsafe already exists which prevents equipped items from being sold, meaning behind the hood equipped items are already kept track of somewhere. Implementation should be simple and straightforward.

### Describe the solution you'd like. What would this look like in the bot?

1. A command, named something like /loadout or /equipped, which displays a list of your currently equipped weapons/armor/mods.

2. A label on currently-equipped items when checking your inventory with /inventory. 

### Describe the alternatives you've considered

One possible alternative would be to remove the ability to equip items before battle, and make equipment setup happen immediately before battling with /fight. This WOULD eliminate a need to see equipped items; however, it would also add an extra step between player command input and gameplay, which I think should be avoided.

**Comment by Ovikx** [comment]
Does `/profile` not solve this issue?

**Comment by Ovikx** [comment]
Closing this on Saturday if there's no response by then

**Comment by FortiethAtom4** [comment]
It does solve the first point, more or less. That's just me being stupid and not knowing about the /profile command. It would be nice to be able to see it all in one interface without swapping through all the tabs, though.

The second point would also be useful as an addition to /inventory.

**Comment by Unlamped** [comment]
you dont need to unequip things besides mods once you reach mod cap, but still you need to unequip something in order to replace it, you can just equip things and it auto overides what you currently have equipped

**Comment by Ovikx** [comment]
@FortiethAtom4 I'm down to make the equipped item indicator for `/inventory`, but I'm leaning against an all-in-one embed because of how massive that embed would be, and consequently, character limits. That said, I'll add your second solution to the todo list

**Comment by Ovikx** [comment]
done, will be pushed in the next update

**Comment by FortiethAtom4** [comment]
Wow, that was fast. Thank you!
