### ISSUE TITLE
inventory page jump

### ISSUE THREAD

**Issue by nut4050** [Ovikx/exalt-public#8]
make it possible to jump to page in the inventory
same as before, my inventory always times out before i can get to any of the good stuff so if you arent tryna add the sort (thouogh you should because it would be awesome) at least make it possible to jump to a page so i dont get re-timed out while clicking back to where i was in my inventory before
because there are some pages in my inv that are just entirely impossible to get to thanks to the timing out

**Comment by Ovikx** [comment]
This would be hard to implement; how about another set of buttons like "<<" and ">>" that increments 5 pages at a time?

**Comment by nut4050** [comment]
👌 👌 👌
